config/routes.rb
Rails.application.routes.draw do
 
  root 'quotes#index'
  get '/authors' => 'authors#index', as: 'authors'
  get '/authors/:author' => 'authors#show', as: 'author_show', :constraints => { :author => /[^\/]+/ }
  get '/category' => 'category#index', as: 'category'
  get '/category/:category' => 'category#show',as: 'category_show', :category => /([^\/])+?/
  get '/about' => 'static_pages#about', as: :about_page
  get '/quotes/all' => 'quotes#all'
  resources :quotes
  resources :users
  resources :user_sessions, only: [ :new, :create, :destroy]
  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
	self.table_name = "quotescopy"
	self.primary_key = "pkey"

  #validate is older version of validation
  #'validates' is "sexy validation version" which shortens code 
  validates :category, 
    presence: true, 
    length: {minimum: 3, maximum: 25}, 
    format: { 
      with: /\A[a-z A-Z &.]+\z/, 
      message: "only allows letters and &." }
  validates :author, 
    presence: true, 
    format: { 
      with: /\A[a-z A-Z &.]+\z/, 
      message: "only allows letters and &." }
  validates :quotetext, 
    presence: true

  #you can't seem to be able to declare methods in a normal way in this model file.
  #you need to make it into a CLASS method like below to be able to use later in the file
  #weird
  def self.mix(arrayX)
      result = []
      arrayX.each do |x|
      result << x.downcase
      result << x.upcase
      result << x.capitalize
    end
    return result
  end

  FORBIDDEN_CATEGORY = mix(['Fuck','Shit', 'Pussy', "Dick", "Penis", 'Cum'])
  validate :category_is_allowed

  def category_is_allowed
    if FORBIDDEN_CATEGORY.include? (category)
          errors.add(:category, "is a restricted bad word category")
    end
  end
  
  scope :sorted, lambda {order("pkey ASC")}
  scope :next, lambda {|pkey| where("pkey > ?", pkey).order("pkey ASC") } # this is the default ordering for AR
  scope :previous, lambda {|pkey| where("pkey < ?", pkey).order("pkey DESC") }

    def next
      Quote.next(self.pkey).first
    end

    def previous
      Quote.previous(self.pkey).first
    end

    def last
      Quote.last
    end

    def first
      Quote.first
    end

	  def text
	 	  read_attribute('quotetext')
	 end

   def self.search(query)
      where("quotetext ILIKE ? OR category ILIKE ? OR author ILIKE ?", "%#{query}%", "%#{query}%", "%#{query}%")
   end

   def self.authors_search(query)
      where("author ILIKE ?", "%#{query}%")
   end

   def self.category_search(query)
      where("category ILIKE ?", "%#{query}%")
   end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]
  before_filter :authenticated, except: [:index, :show, :all]

  def authenticated
    unless current_user
      flash[:danger] = "You need to be admin (or Terry) to perform that action!"
      redirect_to root_path
      return false
    end
  end

  # GET /quotes
  # GET /quotes.json
  def index
    if params[:search]
      @quotes = Quote.search(params[:search]).sorted.paginate(page: params[:page], per_page: 20)
    else
      @quotes = Quote.all.sorted.paginate(page: params[:page], per_page: 50)
    end
    @authors = Quote.uniq.pluck('author').sort
    @category = Quote.uniq.pluck('category').sort
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    respond_to do |format|
      format.html do
        @quote = Quote.find(params[:id])
      end
      format.json { render :json => @quote }
    end
  end

  # GET /quotes/new
  def new
    #new action DISPLAYS the new form page, create PROCESSES the new data
    @quote = Quote.new
    #apparently this doesn't really do anything but good to specify
  end

  def create
    #we don't need a TEMPLATE for create beucase it either redirects or renders
    @quote = Quote.new(quote_params)
    #if save succeeds, redirect to index root page
    if @quote.save
      flash[:success] = "Quote #{@quote.pkey} Created!"
      redirect_to root_path
    #if save fails, redisplay the form so user can fix problems
    else
      render('new')
    end
  end

  # GET /quotes/1/edit
  def edit
    @quote = Quote.find(params[:id])
    @authors = Quote.uniq.pluck('author').sort
    @category = Quote.uniq.pluck('category').sort
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    #find an existing object using form parameters
    @quote = Quote.find(params[:id])
    if @quote.update_attributes(quote_params)
      flash[:notice] = "Quote #{@quote.pkey} Updated!"
      redirect_to(:action => 'show', :id => @quote.id)
    else 
      render('edit')
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote = Quote.find(params[:id]).destroy
    flash[:alert] = "Quote #{@quote.pkey} Deleted!"
    redirect_to root_path
  end


  def author
  end

  def all
    if params[:search]
      @quotes = Quote.search(params[:search]).sorted.paginate(page: params[:page], per_page: 25)
    else
      @quotes = Quote.all.sorted.paginate(page: params[:page], per_page: 1000)
  end

  end

  #it's private so only the controller can use it to do its work. 
  #So it prevents from called as an action.
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:category, :author, :quotetext)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper

	

end

app/views/quotes/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
<div id="error_explanation">
  <h2><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved </h2>
  <ul>
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/quotes/_flash.html.erb
<% if flash[:notice] %>
  <p class="alert alert-info">
    <%= flash[:notice] %>  </p>
<% end %>

<% if flash[:success] %>
  <p class="alert alert-success">
    <%= flash[:success] %>  </p>
<% end %>

<% if flash[:alert] %>
  <p class="alert alert-warning">
    <%= flash[:alert] %>  </p>
<% end %>

<% if flash[:danger] %>
  <p class="alert alert-danger">
    <%= flash[:danger] %>  </p>
<% end %>

app/views/quotes/_form.html.erb
  <p>
    <%= foo.label :category %><br>
    <%= foo.text_field :category, id: 'categoryInput' %>
  </p>
    <p>
    <%= foo.label :author %><br>
    <%= foo.text_field :author, id: 'authorInput' %>
  </p>
    <p>
    <%= foo.label :quotetext, "Quote Text" %><br>
    <%= foo.text_area :quotetext %>
  </p>

app/views/quotes/_quoteslist.html.erb
<%= ajax_links :section_id => "quoteslist" do %>
<%= will_paginate @quotes %> 
<% end %>
  <table class="listing">
    <tr class="header">
      <th>Pkey</th>
      <th>Category</th>
      <th>Author</th>
      <th>Quote Text</th>
      <th>Actions</th>
    </tr>
    <%= ajax_loadzone do %>
    <% @quotes.each do |quote| %>
    <tr class="<%= cycle('odd','even') %>">
      <td><%=quote.pkey %></td>
      <td><%=link_to quote.category, category_show_path(quote.category) %></td>
      <td><%=link_to quote.author, author_show_path(quote.author) %></td>
      <td><%=quote.text %></td>
      <td class="actions">
      <%= link_to "Show", {:action => 'show', :id => quote.id}  %>
      <%= link_to("Edit", {:action => 'edit', :id => quote.id}) %>
        <% if logged_in? %>
        <%= link_to quote_path(quote.id), method: :delete, data: {confirm: "Really delete Quote ##{quote.id}?"} do %><span class=edit>Delete</span>
        <% end %>
      <% end %>
    </td>
    </tr>
    <% end %>
    <% end %>
  </table>
<%= will_paginate @quotes, renderer: BootstrapPagination::Rails %>
<a href="#navclear" class="btn btn-primary" id="moveButtons">Move to Top</a>
<p align='center'><em>End of Page</em></p>

  <div id="jumpbottom"><!-- #this is just place-holder anchor so Move-to-Buttom jump buttons work correctly  --></div>

app/views/quotes/all.html.erb
<% @page_title = "Show All Quotes" %>

<div class='jumbotron'>
<h1>Show All</h1>
</div>

<%= render partial: 'shared/nav' %>

  <div class="page_info"> <%= page_entries_info @quotes, :model => 'quotes' %>  </div>

<div id="FloatingButtons">
<a href="#navclear" class="btn btn-primary">Move to Top</a>
<a href="#jumpbottom"class = "btn btn-primary" >Move to Bottom</a>
</div>

  <table class="listing" style="clear: both;">
    <tr class="header">
      <th>Pkey</th>
      <th>Category</th>
      <th>Author</th>
      <th>Quote Text</th>
      <th>Actions</th>
    </tr>
    <% @quotes.each do |quote| %>
    <tr class="<%= cycle('odd','even') %>">
      <td><%=quote.pkey %></td>
      <td><%=link_to quote.category, category_show_path(quote.category) %></td>
      <td><%=link_to quote.author, author_show_path(quote.author) %></td>
      <td><%=quote.text %></td>
      <td class="actions">
      <%= link_to("Show", {:action => 'show', :id => quote.id}) %>
      <%= link_to("Edit", {:action => 'edit', :id => quote.id}) %>
        <% if logged_in? %>
        <%= link_to quote_path(quote.id), method: :delete, data: {confirm: "Really delete Quote ##{quote.id}?"} do %><span class=edit>Delete</span>
        <% end %>
      <% end %>
    </td>
    </tr>
    <% end %>
  </table>
<%= will_paginate @quotes, renderer: BootstrapPagination::Rails %>


<p align='center'><em>End of Page</em></p>

  <div id="jumpbottom"><!-- #this is just place-holder anchor so Move-to-Buttom jump buttons work correctly  --></div>

app/views/quotes/edit.html.erb
<% @page_title = "Edit Page" %>

<h1>Edit Existing Quote <%=@quote.pkey%> </h1>

<%= display_error_messages(@quote) %>

<%= form_for(@quote) do |f| %>

<%= render partial: 'form', locals: {:foo => f} %>
  
  <button type="submit" class="btn btn-primary">
    Update quote
  </button>

<%= link_to quote_path(@quote.id), :class => "btn btn-primary", method: :delete, data: {confirm: "Really delete Quote ##{@quote.pkey}?"} do %>Delete<% end %>
<% end %>

<div id="ReturnNav">
<%= link_to 'Show', @quote %> |
<%= link_to 'Home', quotes_path %>
</div>

app/views/quotes/index.html.erb
<%= javascript_tag do %>
  window.authorsArray = '<%= @authors.to_json.html_safe %>';
  window.categoryArray = '<%= @category.to_json.html_safe %>';
<% end %>

<div class='jumbotron' id="top">
<h1>Terry's Fav Quotes Database</h1>
</div>

<%= render partial: 'shared/nav' %>
  <%= render partial: 'flash' %>

<a class="btn btn-primary" href="#jumpbottom" style="float: right;
  margin-top: 3%;
  display:inline-block;">Move to Bottom</a>

<%= form_tag(quotes_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Quotes" %>
  <button type="submit" class="btn btn-primary">SEARCH</button>
  <%= link_to "Clear", quotes_path, :class => "btn btn-primary" %>
  <% end %>

  <div class="page_info"> 
  <%= page_entries_info @quotes,  :model => 'quotes' %>  
  </div>
<div id="pagination"> 
<%= will_paginate @quotes, renderer: BootstrapPagination::Rails %> 
</div>
  <table class="listing">
    <tr class="header">
      <th>Pkey</th>
      <th>Category</th>
      <th>Author</th>
      <th>Quote Text</th>
      <th>Actions</th>
    </tr>
    <% @quotes.each do |quote| %>
    <tr class="<%= cycle('odd','even') %>">
      <td><%=quote.pkey %></td>
      <td><%=link_to quote.category, category_show_path(quote.category) %></td>
      <td><%=link_to quote.author, author_show_path(quote.author) %></td>
      <td><%=quote.text %></td>
      <td class="actions">
      <%= link_to "Show", {:action => 'show', :id => quote.id}  %>
      <%= link_to("Edit", {:action => 'edit', :id => quote.id}) %>
        <% if logged_in? %>
        <%= link_to quote_path(quote.id), method: :delete, data: {confirm: "Really delete Quote ##{quote.id}?"} do %><span class=edit>Delete</span>
        <% end %>
      <% end %>
    </td>
    </tr>
    <% end %>
  </table>
<%= will_paginate @quotes, renderer: BootstrapPagination::Rails %>
<a href="#navclear" class="btn btn-primary" id="moveButtons">Move to Top</a>
<p align='center'><em>End of Page</em></p>

  <div id="jumpbottom"><!-- #this is just place-holder anchor so Move-to-Buttom jump buttons work correctly  --></div>

app/views/quotes/new.html.erb
<% @page_title = "Create New Page" %>
<h1>Create New Quote</h1>
  <%=  render(partial: 'error_messages', locals: {:object => @quote}) %> 

<%= form_for (:quote), url: quotes_path do |f| %>
  <%= render partial: 'form', locals: {:foo => f} %>
  <button type="submit" class="btn btn-success">Create Quote</button>
<% end %>

<br>
<%= link_to 'Home', quotes_path, :class => "btn btn-default" %>

app/views/quotes/show.html.erb
<% @page_title = "##{@quote.pkey}" %>

<%= javascript_tag do %>
  window.nextID = '<% if @quote.next.presence %> <%= @quote.next.pkey %> <% end %>';
  window.previousID = '<% if @quote.previous.presence %> <%= @quote.previous.pkey %> <% end %>';
<% end %>

<div class='jumbotron'>
<h1> Quote #<%= @quote.pkey %> </h1>
</div>

<%= render partial: 'shared/nav' %>
<%= render partial: 'flash' %>

<p>ID #<%= @quote.pkey %> </p>
<p><strong>Category: <%= @quote.category %> </strong></p>
<blockquote><p id="quote"><%= @quote.text %></p>
  <%= link_to @quote.author, author_show_path(@quote.author), :id => "author" %><br>
  <%= media_caller(@quote.author) %>
</blockquote>
<p>Updated at <%=@quote.updated_at %>, Created at <%=@quote.created_at %></p>

<ul class="pager">
<% if @quote.previous.presence %> 
<li><%= link_to 'First', @quote.first %></li>  |
<li><%= link_to 'Previous', @quote.previous, :class => "previous" %></li> 
<% end %>
<% if @quote.next.presence %> 
<li><%= link_to 'Next', @quote.next, :class => "next" %></li> | 
<li><%= link_to 'Last', @quote.last %></li>
<% end %>
<p>*Press left and right arrow keys for easy Previous/Next navigation </p>
</ul>

<% if logged_in? %>
<%= link_to 'Edit', edit_quote_path(@quote), :class => "btn btn-primary" %>
<% end %>
<%= link_to 'Back Home', {:action => 'index'}, :class => "btn btn-primary" %>