config/routes.rb
Rails.application.routes.draw do
 
  root 'quotes#index'
  get '/authors' => 'authors#index', as: 'authors'
  get '/authors/:author' => 'authors#show', as: 'author_show', :constraints => { :author => /[^\/]+/ }
  get '/category' => 'category#index', as: 'category'
  get '/category/:category' => 'category#show',as: 'category_show', :category => /([^\/])+?/
  get '/about' => 'static_pages#about', as: :about_page
  get '/quotes/all' => 'quotes#all'
  resources :quotes
  resources :users
  resources :user_sessions, only: [ :new, :create, :destroy]
  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'

end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

	def index
		respond_to do |format|
			format.html do
				if params[:search]
			    	@quotes = Quote.category_search(params[:search])
			    else
					@quotes = Quote.all
		    	end
		    	@category = Quote.uniq.pluck('category').sort
	    	end
	    	format.json {render :json => Quote.uniq.pluck('category').sort}
    	end
	end

	def show
		@category = Quote.find_by(category: params[:category]) or not_found
		respond_to do |format|
			format.html do
				@category = Quote.where(category: params[:category]).sort.paginate(page: params[:page], per_page: 10)
	    	end
	    	format.json {render :json => Quote.where(category: params[:category]).sort}
    	end
	end

end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/category/index.html.erb
<% @page_title = "Category Index" %>
<%= javascript_tag do %>
  window.categoryArray = '<%= @category.to_json.html_safe %>';
<% end %>

<div class='jumbotron' id="top">
<h1>Category Index</h1>
</div>
<%= render partial: 'shared/nav' %>

<%= form_tag(category_path, :method => "get", id: "category-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Category", :class => "typeahead" %>
  <button type="submit" class="btn btn-primary">SEARCH</button>
  <%= link_to "Clear", category_path, :class => "btn btn-primary" %>
  <% end %>

<ol id="CategoryList">
  <% @quotes.uniq.pluck('category').sort.each do |category| %>  
    <li>
    <%= link_to category, category_show_path(category) %> (<%= @quotes.where(category: category).count %>)
    </li>
  <% end %>
</ol>

app/views/category/show.html.erb
<% @page_title = @category.first.category %>

<div class='jumbotron' id="top">
<h1>By Category: <%= @category.first.category %></h1>
</div>
<%= render partial: 'shared/nav' %>

<div id="CategoryNavigation">
  <div id="CategoryNavButtons">
    <%= link_to 'Back to Category Index', category_path, :class => "btn btn-primary" %>
    <% if @category.size > 2 %>
    <a class = "btn btn-primary" href="#jumpbottom">Move to Bottom</a>
    <% end %>
  </div>
</div>

  
  <div id="page_info">
  <%= page_entries_info @category, :model => 'quotes' %><br>
  <%= will_paginate @category %>
  </div>  

<div id="CategoryContainer">
  <% @category.each do |quote| %>
    <div class="<%= cycle('odd', 'even') %>">
    <p>ID #<%= quote.id %> </p>
    <p><strong> <%= quote.category %></strong></p>
    <p> <%= quote.text %> </p>
    <p><em><%= quote.author %></em></p>
    <%= link_to 'Show', quote_path(quote.id) %>
    <% if logged_in? %>
    <%= link_to 'Edit', edit_quote_path(quote.id) %>
    <% end %>
  <hr>
    </div>
  <% end %>
</div>

  <div id="endOfTable">
  <span style="float: right;">
    <%= will_paginate @category, renderer: BootstrapPagination::Rails %>
  </span>
   <% if @category.size > 3 %>
    <a href="#top" class="btn btn-primary" id="moveButtons" style="float:left;">Move to Top</a>
    <% end %>
    </div>


<div id="jumpbottom"><!-- #this is just place-holder anchor so Move-to-Buttom jump buttons work correctly  --></div>