config/routes.rb
Rails.application.routes.draw do
 
  root 'quotes#index'
  get '/authors' => 'authors#index', as: 'authors'
  get '/authors/:author' => 'authors#show', as: 'author_show', :constraints => { :author => /[^\/]+/ }
  get '/category' => 'category#index', as: 'category'
  get '/category/:category' => 'category#show',as: 'category_show', :category => /([^\/])+?/
  get '/about' => 'static_pages#about', as: :about_page
  get '/quotes/all' => 'quotes#all'
  resources :quotes
  resources :users
  resources :user_sessions, only: [ :new, :create, :destroy]
  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'

end

app/controllers/authors_controller.rb
require 'will_paginate/array'

class AuthorsController < ApplicationController

	def index
		respond_to do |format|
			format.html do
				if params[:search]
		    		@authors = Quote.authors_search(params[:search]).uniq.pluck('author').sort
	   			else
					@authors = Quote.uniq.pluck('author').sort
	    		end	
					@quotes = Quote.all
			end
	    	format.json { 
	    		render :json => Quote.uniq.pluck('author').sort
	    	}
	    end
	end

	def show
		if params[:author].end_with?(".json")
			existCheck = Quote.find_by(author: params[:author][0...-5]) or not_found
			if existCheck
				@quotesByAuthor = Quote.where(author: params[:author][0...-5])
				render :json => @quotesByAuthor
			end
		else 
			existCheck = Quote.find_by(author: params[:author]) or not_found
			if existCheck
				@quotesByAuthor = Quote.where(author: params[:author])
				@quotes_paginate = @quotesByAuthor.sort.paginate(page: params[:page], per_page: 10)
				@weirdAuthorsArray = 
				['Asian Proverb', 'Batman', 'Bible', 'Chinese Proverb', 'Terry Bu', 'Fortune Cookie', 'Japanese Proverb', 'Korean Proverb', 'Unknown']
				@authors = Quote.uniq.pluck('author').sort
				@nextAuthor = @authors[(@authors.index(@quotesByAuthor.first.author))+1]
				@previousAuthor = @authors[(@authors.index(@quotesByAuthor.first.author))-1]
			end
		end
	end


end

app/helpers/author_helper.rb
module AuthorHelper



end

app/views/authors/index.html.erb
<% @page_title = "By Authors Index" %>
<%= javascript_tag do %>
  window.authorsArray = '<%= @authors.to_json.html_safe %>';
<% end %>

<div class='jumbotron' id="top">
<h1>By Author Index</h1>
</div>
<%= render partial: 'shared/nav' %>



<%= form_tag(authors_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Authors", :class => "typeahead" %>
  <button type="submit" class="btn btn-primary">SEARCH</button>
  <%= link_to "Clear", authors_path, :class => "btn btn-primary" %>
  <% end %>

<div id="authorsIndex">
  <% i = 0 %>
  <% while i < @authors.size %>
    <ul>
      <% @authors[i..(i+26)].each do |author| %>  
        <li>
        <%= link_to author, author_show_path(author) %> (<%= @quotes.where(author: author).count %>)
        </li>
      <% end %>
    </ul>
    <% i += 27 %>
  <% end %>
</div>

app/views/authors/show.html.erb
<% @page_title = @quotesByAuthor.first.author %>

<div class='jumbotron' id="top">
<h1>By Author: <%= @quotesByAuthor.first.author %> </h1>
</div>

<%= render partial:'shared/nav' %>

<div id="authorShowMainNav">
<%= link_to 'Back to Authors Index', authors_path, :class => "btn btn-primary"  %>
<% if @quotesByAuthor.size >= 4 %>
<a class = "btn btn-primary" href="#jumpbottom">Move to Bottom</a>
<% end %>
</div>
<div id="nextPrevNav">
<span id="authorNav">
  <% if @previousAuthor.presence %>
  <%= link_to "Previous Author: #{@previousAuthor}", author_show_path(@previousAuthor) %>
  <br>
  <% end %>
  <% if @nextAuthor.presence %>
  <%= link_to "Next Author: #{@nextAuthor}", author_show_path(@nextAuthor) %>
  <% end %>
</span>
</div>

<hr>

<div class="media">
<a href='#', class='pull-left'>
  <%= media_caller(@quotesByAuthor.first.author) %>
</a>
   <div class="media-body">
      <h4 class="media-heading">
      <!--to prevent the "Google lookup author" dialogue on authors that don't really needed to be looked up like my name or Fortune Cookie --> 
<% if !@weirdAuthorsArray.include? @quotesByAuthor.first.author %>
      You have <%= pluralize(@quotesByAuthor.size, 'quote') %> by <a target=”_blank” href="http://www.google.com/search?q=<%=@quotesByAuthor.first.author%>"><%= @quotesByAuthor.first.author %></a> (Lookup author)
      <% if @quotesByAuthor.size > 10 %>
      <br><br>
      <span id="page_entries">
        <%= page_entries_info @quotes_paginate, :model => 'quotes' %> 
      </span>
      <br>
      <% end %>
      <%= will_paginate @quotes_paginate %>
      <% else %>
      You have <%= pluralize(@quotesByAuthor.size, 'quote') %> by <%=@quotesByAuthor.first.author%>.
      <% end %>
   </div>
   </div>

<hr>
<% @quotes_paginate.sort.each do |quote| %>
<div class="<%= cycle('odd', 'even') %>">
  <p>ID # <%=quote.pkey %> </p>
  <p><strong> <%= quote.category %></strong></p>
  <p> <%= quote.text %> </p>
  <p><em><%= quote.author %></em></p>
  <%= link_to 'Show', quote_path(quote.id) %>
  <%= link_to 'Edit', edit_quote_path(quote.id) %>
  <hr>
  </div>
<% end %>
<%= will_paginate @quotes_paginate %>
<p><em>End of Page</em></p>
<div id="jumpbottom"></div>
<% if @quotesByAuthor.size >= 4 %>
  <a href="#top" class="btn btn-primary" id="movebutton">Move to Top</a>
<% end %>